<?php

namespace AppBundle\Entity;

/**
 * TramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteRepository extends \Doctrine\ORM\EntityRepository
{
}
